# These are supported funding model platforms
custom: ['https://github.com/OffcierCia/support', 'https://officercia.mirror.xyz/Uc1sf64yUCb0uo1DxR_nuif5EmMPs-RAshDyoAGEZZY', 'https://etherscan.io/address/0xB25C5E8fA1E53eEb9bE3421C59F6A66B786ED77A', 'https://gitcoin.co/grants/3150/defi-web3-developer-roadmap']
